### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hippy2094/page2png#1]
```
Nice project!
I have taken a snapshot of my site http://www.techoffer.in/ using this tool and 
a standard snapshot software Fast Stone Capture. Differences are in the image 
quality. Some images haven't been loaded while using this tool. But overall a 
good result to start with. I am attaching both  images.
```

Original issue reported on code.google.com by `insights...@gmail.com` on 21 Feb 2013 at 9:31

Attachments:
* [techoffer page2png.png](https://storage.googleapis.com/google-code-attachments/page2png/issue-1/comment-0/techoffer page2png.png)
* [techoffer FSC.png](https://storage.googleapis.com/google-code-attachments/page2png/issue-1/comment-0/techoffer FSC.png)

**Comment by hippy2094** [comment]
Fixed way back in 2013
